#!/bin/bash

echo "🔧 Fixing THREE.Clock deprecation warning..."
echo ""
echo "⚠️  Warning: THREE.Clock deprecated, use THREE.Timer instead"
echo ""
echo "📦 Current versions:"
echo "   - three: ^0.184.0"
echo "   - @react-three/fiber: ^9.6.1"
echo "   - @react-three/drei: ^10.7.7"
echo ""
echo "🔄 Solution options:"
echo ""
echo "Option 1: Update packages (Recommended)"
echo "   cd frontend"
echo "   npm update three @react-three/fiber @react-three/drei"
echo ""
echo "Option 2: Suppress warning (Temporary)"
echo "   Add to next.config.js:"
echo "   webpack: (config) => {"
echo "     config.ignoreWarnings = ["
echo "       { module: /node_modules\/three/ },"
echo "     ];"
echo "     return config;"
echo "   }"
echo ""
echo "Option 3: Wait for @react-three/fiber update"
echo "   The warning is from internal R3F code, not our code"
echo "   R3F will update to use THREE.Timer in future release"
echo ""
echo "ℹ️  Note: This is just a deprecation warning, not an error"
echo "   Your app still works perfectly fine"
echo ""
echo "🎯 Recommended action:"
echo "   npm update three @react-three/fiber @react-three/drei"
